<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('adminhtml')->__('Additional Cache Management') ?></h3></td><td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/clearapc/index')?>')" type="button" class="scalable">
                <span><?php echo Mage::helper('adminhtml')->__('Flush APC Cache') ?></span>
            </button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('APC user and system cache.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanImagesUrl()?>')" type="button" class="scalable"><span><?php echo Mage::helper('adminhtml')->__('Flush Catalog Images Cache') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Pregenerated product images files.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanMediaUrl()?>')" type="button" class="scalable"><span><?php echo Mage::helper('adminhtml')->__('Flush JavaScript/CSS Cache') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Themes JavaScript and CSS files combined to one file.')?>
        </td>
    </tr>
</table>
<?php echo $this->getChildHtml(); ?>
